### ISSUE TITLE
Npm build fails requiring babel-register

### ISSUE THREAD

**Issue by rmhsilva** [glazedio/glazed#137]
* **Glazed Version**: 1.0.0-alpha.1
* **Node Version**: v6.0.0
* **Platform**: Darwin catamaran.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64 i386 MacBookPro8,2 Darwin

Hi!

Quick description of issue: I perform a new `git clone` of glazed (master), update the .env file as required, and run `npm install`. In addition to the notice of jade being deprecated (replaced by pug), the build step fails with the following:

```
> glazed@1.0.0-alpha.1 postinstall /Users/user/glazed
> npm run build


> glazed@1.0.0-alpha.1 build /Users/user/glazed
> gulp build

[19:41:09] Requiring external module babel-register
module.js:440
    throw err;
    ^

Error: Cannot find module 'babel-regenerator-runtime'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (gulpfile.babel.js:4:1)
    at Module._compile (module.js:541:32)
    at loader (/Users/user/glazed/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/user/glazed/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/user/.nvm/versions/node/v6.0.0/bin/node" "/Users/user/.nvm/versions/node/v6.0.0/bin/npm" "run" "build"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! glazed@1.0.0-alpha.1 build: `gulp build`
npm ERR! Exit status 1
```

**Comment by HemanthKona** [comment]
Hi @rmhsilva 

I had similar issue, so installing the missing package 'babel-regenerator-runtime' fixed it. 

```sh
sudo npm install babel-regenerator-runtime
```

**Comment by rmhsilva** [comment]
Hi @HemanthKona, thanks for the pointer! That seems to fix the first issue, but I've encountered a second issue. This looks completely separate so I should probably open another...

It looks like, contrary to the Glazed instructions, I need to *copy* .env.example and modify, rather than rename it.

```
> glazed@1.0.0-alpha.1 build /Users/user/glazed
> gulp build

[18:20:06] Requiring external module babel-register
(node:16878) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Error: ENOENT: no such file or directory, open '.env.example'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.module.exports.config (/Users/user/glazed/node_modules/dotenv-safe/index.js:26:42)
    at Object.<anonymous> (/Users/user/glazed/gulpfile.babel.js:121:22)
    at Module._compile (module.js:541:32)
    at loader (/Users/user/glazed/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/user/glazed/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
```

**Comment by azide0x37** [comment]
@rmhsilva Might follow up with that in https://github.com/glazedio/glazed/issues/135
