### ISSUE TITLE
Gulp: Unexpected token import

### ISSUE THREAD

**Issue by Jordy** [glazedio/glazed#139]
* **Version**:1.0.0-alpha.1
* **Platform**: Ubuntu 12.04 LTS (Vagrant)
* **Subsystem**: Node v6.0.0, NPM v3.8.6

Hi,

So I've cloned the Glazed repository and run npm install. When I attempt to run
`gulp`
I get the following errors.

```
vagrant@precise64:/var/www/glazed$ gulp
[09:14:31] Failed to load external module babel-register
[09:14:31] Failed to load external module babel-core/register
[09:14:31] Failed to load external module babel/register
/var/www/glazed/gulpfile.babel.js:3
import 'babel-polyfill';
^^^^^^
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:24:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp-cli/index.js:150:63)
```

I can confirm that babel-cli, babel-core, babel-register are in the node_modules folder.
I've taken a look at #137 , but it appears to be a slightly different issue towards the end of the thread.

 Is there a package missing or is this an error in the project?

**Comment by azide0x37** [comment]
Had this same issue upon spawning a fresh VM. Babel isn't loading(?) prior to getting to the gulpfile, and not recognising the new `import` syntax (afaik; am js noob)

`npm i --save-dev babel-cli` should work, but `npm install --save-dev babel-preset-es2015` solved this for me. Not sure how to make this automatic upon `npm install`

http://stackoverflow.com/questions/33604470/unexpected-token-import-in-nodejs5-and-babel

**Comment by niftylettuce** [comment]
It should be working OK now, can you try?

**Comment by niftylettuce** [comment]
I released v2 on GitHub here.
